name: ButtonPromote
main: me.furt.buttonpromote.ButtonPromote
version: ${project.version}
authors: [furt, _InnoKo_]
description: ButtonPromote takes the common button and pressure plate and extends on them.
depend: [Vault]
database: true
commands:
    buttonpromote:
      aliases:
        - bp
        - bpromote
      description: Main command.
      usage: /<command>
