name: ButtonPromote
main: me.iMint.ButtonPromote.ButtonPromote
version: 2.3.1
authors: [furt, _InnoKo_]
depend: [Vault]
database: true
commands:
    buttonpromote:
      aliases:
        - bp
        - bpromote
      description: Main command.
      usage: /<command>
            